//! Regression test: every generated compatibility response must be a
//! well-formed TL object that the declared return type can parse back.
//!
//! Generated by `tools/gen_compat.py`; do not edit by hand.

use grammers_tl_types as tl;
use grammers_tl_types::Deserializable;
use telegram_server::compat;

fn roundtrip<T: Deserializable>(ctor: u32, label: &str) {
    let body = compat::default_response(ctor)
        .unwrap_or_else(|| panic!("{label}: no default response for {ctor:#x}"));
    let mut cur = tl::Cursor::from_slice(&body);
    T::deserialize(&mut cur)
        .unwrap_or_else(|e| panic!("{label}: {ctor:#x} is not valid TL: {e:?}"));
    assert_eq!(
        cur.pos(),
        body.len(),
        "{label}: {ctor:#x} left trailing bytes"
    );
}

#[test]
fn namespace_None() {
    roundtrip::<tl::enums::RpcDropAnswer>(0x58e4a740, "None::RpcDropAnswer");
    roundtrip::<tl::enums::ResPq>(0x60469778, "None::ReqPq");
    roundtrip::<tl::enums::Pong>(0x7abe77ec, "None::Ping");
    roundtrip::<tl::enums::ResPq>(0xbe7e8ef1, "None::ReqPqMulti");
    roundtrip::<tl::enums::DestroyAuthKeyRes>(0xd1435160, "None::DestroyAuthKey");
    roundtrip::<tl::enums::ServerDhParams>(0xd712e4be, "None::ReqDhParams");
    roundtrip::<tl::enums::DestroySessionRes>(0xe7512126, "None::DestroySession");
    roundtrip::<tl::enums::Pong>(0xf3427b8c, "None::PingDelayDisconnect");
    roundtrip::<tl::enums::SetClientDhParamsAnswer>(0xf5045f1f, "None::SetClientDhParams");
}

#[test]
fn namespace_account() {
    roundtrip::<tl::enums::account::EmailVerified>(0x32da4cf, "account::VerifyEmail");
    roundtrip::<tl::enums::ReactionsNotifySettings>(
        0x6dd654c,
        "account::GetReactionsNotifySettings",
    );
    roundtrip::<tl::enums::account::WallPapers>(0x7967d36, "account::GetWallPapers");
    roundtrip::<tl::enums::AccountDaysTtl>(0x8fc711d, "account::GetAccountTtl");
    roundtrip::<tl::enums::account::EmojiStatuses>(0xf578105, "account::GetRecentEmojiStatuses");
    roundtrip::<tl::enums::PeerNotifySettings>(0x12b3ad31, "account::GetNotifySettings");
    roundtrip::<bool>(0x18201aae, "account::ClearRecentEmojiStatuses");
    roundtrip::<tl::enums::account::WebAuthorizations>(0x182e6d6f, "account::GetWebAuthorizations");
    roundtrip::<tl::enums::account::PaidMessagesRevenue>(
        0x19ba4a67,
        "account::GetPaidMessagesRevenue",
    );
    roundtrip::<tl::enums::auth::SentCode>(0x1b3faa88, "account::SendConfirmPhoneCode");
    roundtrip::<tl::enums::Document>(0x1c3db333, "account::UploadTheme");
    roundtrip::<bool>(0x1d2652ee, "account::FinishTakeoutSession");
    roundtrip::<tl::enums::GlobalPrivacySettings>(0x1edaaac2, "account::SetGlobalPrivacySettings");
    roundtrip::<bool>(0x2442485e, "account::SetAccountTtl");
    roundtrip::<bool>(0x2714d86c, "account::CheckUsername");
    roundtrip::<tl::enums::Theme>(0x2bf40ccc, "account::UpdateTheme");
    roundtrip::<bool>(0x2d01b9ef, "account::ResetWebAuthorization");
    roundtrip::<tl::enums::account::EmojiStatuses>(
        0x2e7b4543,
        "account::GetCollectibleEmojiStatuses",
    );
    roundtrip::<tl::enums::ReactionsNotifySettings>(
        0x316ce548,
        "account::SetReactionsNotifySettings",
    );
    roundtrip::<tl::enums::EmojiList>(0x35a9e0d5, "account::GetChannelRestrictedStatusEmojis");
    roundtrip::<bool>(0x38df3532, "account::UpdateDeviceLocked");
    roundtrip::<tl::enums::Theme>(0x3a5869ec, "account::GetTheme");
    roundtrip::<tl::enums::account::SavedRingtone>(0x3dea5b03, "account::SaveRingtone");
    roundtrip::<tl::enums::User>(0x3e0bdd7c, "account::UpdateUsername");
    roundtrip::<bool>(0x40f48462, "account::ChangeAuthorizationSettings");
    roundtrip::<tl::enums::account::PasskeyRegistrationOptions>(
        0x429547e8,
        "account::InitPasskeyRegistration",
    );
    roundtrip::<tl::enums::account::TmpPassword>(0x449e0b51, "account::GetTmpPassword");
    roundtrip::<bool>(0x4b00e066, "account::UpdateBusinessWorkHours");
    roundtrip::<bool>(0x4c9409f6, "account::DeclinePasswordReset");
    roundtrip::<bool>(0x4dd3a7f6, "account::VerifyPhone");
    roundtrip::<tl::enums::account::ConnectedBots>(0x4ea4c80f, "account::GetConnectedBots");
    roundtrip::<tl::enums::Updates>(0x53577479, "account::GetNotifyExceptions");
    roundtrip::<bool>(0x53bc0020, "account::DeleteAutoSaveExceptions");
    roundtrip::<tl::enums::account::Password>(0x548a30f5, "account::GetPassword");
    roundtrip::<tl::enums::account::ResolvedBusinessChatLinks>(
        0x5492e5ee,
        "account::ResolveBusinessChatLink",
    );
    roundtrip::<tl::enums::Passkey>(0x55b41fd6, "account::RegisterPasskey");
    roundtrip::<tl::enums::account::WebBrowserSettings>(
        0x56655768,
        "account::GetWebBrowserSettings",
    );
    roundtrip::<tl::enums::account::AutoDownloadSettings>(
        0x56da0b3f,
        "account::GetAutoDownloadSettings",
    );
    roundtrip::<bool>(0x58d6b376, "account::ToggleUsername");
    roundtrip::<bool>(0x5dee78b0, "account::SetMainProfileTab");
    roundtrip::<bool>(0x5e437ed9, "account::DisablePeerConnectedBot");
    roundtrip::<bool>(0x5f2178c3, "account::ConfirmPhone");
    roundtrip::<bool>(0x60073674, "account::DeleteBusinessChatLink");
    roundtrip::<tl::enums::Updates>(0x60ed4229, "account::ToggleWebBrowserSettingsException");
    roundtrip::<bool>(0x646e1097, "account::ToggleConnectedBotPaused");
    roundtrip::<tl::enums::Theme>(0x652e4400, "account::CreateTheme");
    roundtrip::<Vec<tl::enums::WallPaper>>(0x65ad71dc, "account::GetMultiWallPapers");
    roundtrip::<bool>(0x6628562c, "account::UpdateStatus");
    roundtrip::<tl::enums::Updates>(0x66a08c7e, "account::UpdateConnectedBot");
    roundtrip::<bool>(0x66cdafc4, "account::UpdateBusinessGreetingMessage");
    roundtrip::<bool>(0x67ed1f68, "account::ConfirmBotConnection");
    roundtrip::<bool>(0x682d2594, "account::ResetWebAuthorizations");
    roundtrip::<bool>(0x684d214e, "account::UpdateColor");
    roundtrip::<bool>(0x6a0d3206, "account::UnregisterDevice");
    roundtrip::<bool>(0x6c5a5b37, "account::SaveWallPaper");
    roundtrip::<tl::enums::account::BusinessChatLinks>(0x6f70dde1, "account::GetBusinessChatLinks");
    roundtrip::<tl::enums::User>(0x70c32edb, "account::ChangePhone");
    roundtrip::<tl::enums::account::Themes>(0x7206e458, "account::GetThemes");
    roundtrip::<Vec<tl::enums::SecureValue>>(0x73665bc2, "account::GetSecureValue");
    roundtrip::<tl::enums::Updates>(0x76a86270, "account::GetBotBusinessConnection");
    roundtrip::<bool>(0x76f36233, "account::SaveAutoDownloadSettings");
    roundtrip::<tl::enums::account::EmojiStatuses>(
        0x7727a7d5,
        "account::GetChannelDefaultEmojiStatuses",
    );
    roundtrip::<tl::enums::User>(0x78515775, "account::UpdateProfile");
    roundtrip::<bool>(0x7a7f2a15, "account::ResendPasswordEmail");
    roundtrip::<tl::enums::auth::SentCode>(0x82574ae5, "account::SendChangePhoneCode");
    roundtrip::<tl::enums::Document>(0x831a83a2, "account::UploadRingtone");
    roundtrip::<bool>(0x84be5b93, "account::UpdateNotifySettings");
    roundtrip::<tl::enums::account::WebBrowserSettings>(
        0x86a0765d,
        "account::DeleteWebBrowserSettingsExceptions",
    );
    roundtrip::<tl::enums::BusinessChatLink>(0x8851e68e, "account::CreateBusinessChatLink");
    roundtrip::<tl::enums::SecureValue>(0x899fe31d, "account::SaveSecureValue");
    roundtrip::<tl::enums::account::ContentSettings>(0x8b9b4dae, "account::GetContentSettings");
    roundtrip::<tl::enums::BusinessChatLink>(0x8c3410af, "account::EditBusinessChatLink");
    roundtrip::<tl::enums::account::Takeout>(0x8ef3eab0, "account::InitTakeoutSession");
    roundtrip::<bool>(0x8fdf1920, "account::ConfirmPasswordEmail");
    roundtrip::<tl::enums::EmojiList>(0x915860ae, "account::GetDefaultGroupPhotoEmojis");
    roundtrip::<tl::enums::account::ResetPasswordResult>(0x9308ce1b, "account::ResetPassword");
    roundtrip::<tl::enums::account::SentEmailCode>(0x98e037bb, "account::SendVerifyEmailCode");
    roundtrip::<tl::enums::account::WebBrowserSettings>(
        0x9adf82fe,
        "account::UpdateWebBrowserSettings",
    );
    roundtrip::<tl::enums::account::PasswordSettings>(0x9cd4eaf9, "account::GetPasswordSettings");
    roundtrip::<bool>(0x9e6b131a, "account::UpdateBusinessLocation");
    roundtrip::<bool>(0x9f07c728, "account::GetContactSignUpNotification");
    roundtrip::<bool>(0xa26a7fa5, "account::UpdateBusinessAwayMessage");
    roundtrip::<bool>(0xa2c0cf74, "account::DeleteAccount");
    roundtrip::<bool>(0xa59b102f, "account::UpdatePasswordSettings");
    roundtrip::<tl::enums::auth::SentCode>(0xa5a356f9, "account::SendVerifyPhoneCode");
    roundtrip::<tl::enums::EmojiList>(0xa60ab9ce, "account::GetDefaultBackgroundEmojis");
    roundtrip::<bool>(0xa614d034, "account::UpdateBusinessIntro");
    roundtrip::<tl::enums::account::AuthorizationForm>(0xa929597a, "account::GetAuthorizationForm");
    roundtrip::<tl::enums::account::AutoSaveSettings>(0xadcbbcda, "account::GetAutoSaveSettings");
    roundtrip::<bool>(0xb26732a9, "account::SaveMusic");
    roundtrip::<Vec<tl::enums::SecureValue>>(0xb288bc7d, "account::GetAllSecureValues");
    roundtrip::<bool>(0xb574b16b, "account::SetContentSettings");
    roundtrip::<bool>(0xb880bc4b, "account::DeleteSecureValue");
    roundtrip::<bool>(0xb9d9a38d, "account::ToggleSponsoredMessages");
    roundtrip::<bool>(0xbb3b9804, "account::ResetWallPapers");
    roundtrip::<bool>(0xbf899aa0, "account::SetAuthorizationTtl");
    roundtrip::<bool>(0xc1cbd5b6, "account::CancelPasswordEmail");
    roundtrip::<bool>(0xc5ba3d86, "account::ReportPeer");
    roundtrip::<bool>(0xc727bb3b, "account::InstallTheme");
    roundtrip::<tl::enums::account::PrivacyRules>(0xc9f81ce8, "account::SetPrivacy");
    roundtrip::<bool>(0xca8ae8ba, "account::InvalidateSignInCodes");
    roundtrip::<bool>(0xcc6e0c11, "account::UpdateBirthday");
    roundtrip::<bool>(0xcff43f61, "account::SetContactSignUpNotification");
    roundtrip::<tl::enums::account::Themes>(0xd638de89, "account::GetChatThemes");
    roundtrip::<tl::enums::account::EmojiStatuses>(0xd6753386, "account::GetDefaultEmojiStatuses");
    roundtrip::<bool>(0xd69b8361, "account::SaveAutoSaveSettings");
    roundtrip::<bool>(0xd94305e0, "account::UpdatePersonalChannel");
    roundtrip::<tl::enums::account::PrivacyRules>(0xdadbc950, "account::GetPrivacy");
    roundtrip::<bool>(0xdb7e1747, "account::ResetNotifySettings");
    roundtrip::<bool>(0xdf77f3bc, "account::ResetAuthorization");
    roundtrip::<tl::enums::account::SavedMusicIds>(0xe09d5faf, "account::GetSavedMusicIds");
    roundtrip::<tl::enums::account::SavedRingtones>(0xe1902288, "account::GetSavedRingtones");
    roundtrip::<tl::enums::EmojiList>(0xe2750328, "account::GetDefaultProfilePhotoEmojis");
    roundtrip::<tl::enums::account::Authorizations>(0xe320c158, "account::GetAuthorizations");
    roundtrip::<tl::enums::WallPaper>(0xe39a8f03, "account::UploadWallPaper");
    roundtrip::<tl::enums::account::ChatThemes>(0xe42ce9c9, "account::GetUniqueGiftChatThemes");
    roundtrip::<tl::enums::account::Passkeys>(0xea1f0c52, "account::GetPasskeys");
    roundtrip::<tl::enums::GlobalPrivacySettings>(0xeb2b4cf6, "account::GetGlobalPrivacySettings");
    roundtrip::<bool>(0xec86017a, "account::RegisterDevice");
    roundtrip::<bool>(0xef500eab, "account::ReorderUsernames");
    roundtrip::<bool>(0xf257106c, "account::SaveTheme");
    roundtrip::<bool>(0xf3ed4c73, "account::AcceptAuthorization");
    roundtrip::<bool>(0xf5b5563f, "account::DeletePasskey");
    roundtrip::<bool>(0xfa8cc6f5, "account::ReportProfilePhoto");
    roundtrip::<bool>(0xfbd3de6b, "account::UpdateEmojiStatus");
    roundtrip::<tl::enums::WallPaper>(0xfc8ddbea, "account::GetWallPaper");
    roundtrip::<bool>(0xfe2eda76, "account::ToggleNoPaidMessagesException");
    roundtrip::<bool>(0xfeed5769, "account::InstallWallPaper");
}

#[test]
fn namespace_auth() {
    roundtrip::<bool>(0xd36bf79, "auth::CheckRecoveryPassword");
    roundtrip::<bool>(0x1f040578, "auth::CancelCode");
    roundtrip::<tl::enums::auth::Authorization>(0x2db873a9, "auth::ImportWebTokenAuthorization");
    roundtrip::<tl::enums::auth::Authorization>(0x37096c70, "auth::RecoverPassword");
    roundtrip::<tl::enums::auth::LoggedOut>(0x3e72ba19, "auth::LogOut");
    roundtrip::<tl::enums::auth::PasskeyLoginOptions>(0x518ad0b7, "auth::InitPasskeyLogin");
    roundtrip::<tl::enums::auth::SentCode>(0x56e59f9c, "auth::CheckPaidAuth");
    roundtrip::<tl::enums::auth::Authorization>(0x67a3ff2c, "auth::ImportBotAuthorization");
    roundtrip::<tl::enums::auth::SentCode>(0x7e960193, "auth::ResetLoginEmail");
    roundtrip::<tl::enums::auth::Authorization>(0x8d52a951, "auth::SignIn");
    roundtrip::<bool>(0x8e39261e, "auth::RequestFirebaseSms");
    roundtrip::<bool>(0x8e48a188, "auth::DropTempAuthKeys");
    roundtrip::<tl::enums::auth::LoginToken>(0x95ac5ce4, "auth::ImportLoginToken");
    roundtrip::<tl::enums::auth::Authorization>(0x9857ad07, "auth::FinishPasskeyLogin");
    roundtrip::<bool>(0x9fab0d1a, "auth::ResetAuthorizations");
    roundtrip::<tl::enums::auth::Authorization>(0xa57a7dad, "auth::ImportAuthorization");
    roundtrip::<tl::enums::auth::SentCode>(0xa677244f, "auth::SendCode");
    roundtrip::<tl::enums::auth::Authorization>(0xaac7b717, "auth::SignUp");
    roundtrip::<tl::enums::auth::LoginToken>(0xb7e085fe, "auth::ExportLoginToken");
    roundtrip::<tl::enums::auth::SentCode>(0xcae47523, "auth::ResendCode");
    roundtrip::<bool>(0xcb9deff6, "auth::ReportMissingCode");
    roundtrip::<bool>(0xcdd42a05, "auth::BindTempAuthKey");
    roundtrip::<tl::enums::auth::Authorization>(0xd18b4d16, "auth::CheckPassword");
    roundtrip::<tl::enums::auth::PasswordRecovery>(0xd897bc66, "auth::RequestPasswordRecovery");
    roundtrip::<tl::enums::auth::ExportedAuthorization>(0xe5bfffcd, "auth::ExportAuthorization");
    roundtrip::<tl::enums::Authorization>(0xe894ad4d, "auth::AcceptLoginToken");
}

#[test]
fn namespace_bots() {
    roundtrip::<bool>(0x517165a, "bots::SetBotCommands");
    roundtrip::<bool>(0x53ca973, "bots::ToggleUsername");
    roundtrip::<bool>(0x6de6392, "bots::ToggleUserEmojiStatusPermission");
    roundtrip::<tl::enums::DataJson>(0x87fc5e7, "bots::InvokeWebViewCustomMethod");
    roundtrip::<bool>(0x10cf3123, "bots::SetBotInfo");
    roundtrip::<bool>(0x1359f4e6, "bots::CanSendMessage");
    roundtrip::<tl::enums::BotPreviewMedia>(0x17aeb75a, "bots::AddPreviewMedia");
    roundtrip::<tl::enums::bots::AccessSettings>(0x213853a3, "bots::GetAccessSettings");
    roundtrip::<bool>(0x2d0135b3, "bots::DeletePreviewMedia");
    roundtrip::<bool>(0x31813cd8, "bots::EditAccessSettings");
    roundtrip::<tl::enums::bots::RequestedButton>(0x31a2a35e, "bots::RequestWebViewButton");
    roundtrip::<bool>(0x3d8de0f9, "bots::ResetBotCommands");
    roundtrip::<tl::enums::bots::PreviewInfo>(0x423ab3ad, "bots::GetPreviewInfo");
    roundtrip::<bool>(0x4504d54f, "bots::SetBotMenuButton");
    roundtrip::<bool>(0x50077589, "bots::CheckDownloadFileParams");
    roundtrip::<tl::enums::StarRefProgram>(0x778b5ab3, "bots::UpdateStarRefProgram");
    roundtrip::<bool>(0x788464e1, "bots::SetBotBroadcastDefaultAdminRights");
    roundtrip::<tl::enums::BotPreviewMedia>(0x8525606f, "bots::EditPreviewMedia");
    roundtrip::<bool>(0x87f2219b, "bots::CheckUsername");
    roundtrip::<bool>(0x8b89dfbd, "bots::SetCustomVerification");
    roundtrip::<bool>(0x925ec9ea, "bots::SetBotGroupDefaultAdminRights");
    roundtrip::<bool>(0x9709b1c2, "bots::ReorderUsernames");
    roundtrip::<tl::enums::BotMenuButton>(0x9c60eb28, "bots::GetBotMenuButton");
    roundtrip::<tl::enums::users::Users>(0xa1b70815, "bots::GetBotRecommendations");
    roundtrip::<Vec<tl::enums::BotPreviewMedia>>(0xa2a5594d, "bots::GetPreviewMedias");
    roundtrip::<tl::enums::DataJson>(0xaa2769ed, "bots::SendCustomRequest");
    roundtrip::<Vec<tl::enums::User>>(0xb0711d83, "bots::GetAdminedBots");
    roundtrip::<bool>(0xb627f3aa, "bots::ReorderPreviewMedias");
    roundtrip::<tl::enums::bots::ExportedBotToken>(0xbd0d99eb, "bots::ExportBotToken");
    roundtrip::<tl::enums::KeyboardButton>(0xbf25b7f3, "bots::GetRequestedWebViewButton");
    roundtrip::<tl::enums::bots::PopularAppBots>(0xc2510192, "bots::GetPopularAppBots");
    roundtrip::<tl::enums::bots::BotInfo>(0xdcd914fd, "bots::GetBotInfo");
    roundtrip::<Vec<tl::enums::BotCommand>>(0xe34c0dd6, "bots::GetBotCommands");
    roundtrip::<tl::enums::User>(0xe5b17f2b, "bots::CreateBot");
    roundtrip::<bool>(0xe6213f4d, "bots::AnswerWebhookJsonquery");
    roundtrip::<bool>(0xe71a4810, "bots::SetJoinChatResults");
    roundtrip::<bool>(0xed9f30c5, "bots::UpdateUserEmojiStatus");
    roundtrip::<tl::enums::Updates>(0xf132e3ef, "bots::AllowSendMessage");
}

#[test]
fn namespace_channels() {
    roundtrip::<tl::enums::messages::ChatFull>(0x8736a09, "channels::GetFullChannel");
    roundtrip::<bool>(0xa245dd3, "channels::DeactivateAllUsernames");
    roundtrip::<tl::enums::messages::Chats>(0xa7f6bbb, "channels::GetChannels");
    roundtrip::<tl::enums::Updates>(0xb290c69, "channels::ConvertToGigagroup");
    roundtrip::<tl::enums::Updates>(0xecc2618, "channels::ToggleJoinRequest");
    roundtrip::<bool>(0x10e6bd2c, "channels::CheckUsername");
    roundtrip::<tl::enums::messages::InactiveChats>(0x11e831ee, "channels::GetInactiveChannels");
    roundtrip::<tl::enums::Updates>(0x167fc0a1, "channels::ToggleAutotranslation");
    roundtrip::<tl::enums::SearchPostsFlood>(0x22567115, "channels::CheckSearchPostsFlood");
    roundtrip::<tl::enums::messages::Chats>(0x25a71742, "channels::GetChannelRecommendations");
    roundtrip::<tl::enums::channels::AdminLogResults>(0x33ddf480, "channels::GetAdminLog");
    roundtrip::<bool>(0x3514b3de, "channels::UpdateUsername");
    roundtrip::<bool>(0x3583fcb1, "channels::SetMainProfileTab");
    roundtrip::<tl::enums::messages::AffectedHistory>(
        0x367544db,
        "channels::DeleteParticipantHistory",
    );
    roundtrip::<bool>(0x3cd930b7, "channels::SetEmojiStickers");
    roundtrip::<tl::enums::Updates>(0x3ff75734, "channels::ToggleForum");
    roundtrip::<bool>(0x40582bb2, "channels::SetDiscussionGroup");
    roundtrip::<tl::enums::Updates>(0x418d549c, "channels::ToggleSignatures");
    roundtrip::<tl::enums::Updates>(0x4b12327b, "channels::UpdatePaidMessagesPrice");
    roundtrip::<bool>(0x50f24105, "channels::ToggleUsername");
    roundtrip::<tl::enums::Updates>(0x566decd0, "channels::EditTitle");
    roundtrip::<bool>(0x58e63f6d, "channels::EditLocation");
    roundtrip::<tl::enums::Updates>(0x68f3e4eb, "channels::ToggleAntiSpam");
    roundtrip::<tl::enums::Updates>(0x6a6e7854, "channels::ToggleParticipantsHidden");
    roundtrip::<tl::enums::channels::ChannelParticipants>(0x77ced9d0, "channels::GetParticipants");
    roundtrip::<tl::enums::messages::ChatInviteJoinResult>(0x7f6a1e22, "channels::JoinChannel");
    roundtrip::<tl::enums::messages::Chats>(0x8341ecc0, "channels::GetLeftChannels");
    roundtrip::<tl::enums::messages::AffectedMessages>(0x84c1fd4e, "channels::DeleteMessages");
    roundtrip::<tl::enums::Updates>(0x91006707, "channels::CreateChannel");
    roundtrip::<tl::enums::Updates>(0x96e6cd81, "channels::EditBanned");
    roundtrip::<tl::enums::Updates>(0x9738bb15, "channels::ToggleViewForumAsMessages");
    roundtrip::<tl::enums::Updates>(0x9a98ad68, "channels::EditAdmin");
    roundtrip::<tl::enums::Updates>(0x9ae91519, "channels::RestrictSponsoredMessages");
    roundtrip::<tl::enums::Updates>(0x9baa9647, "channels::DeleteHistory");
    roundtrip::<tl::enums::channels::ChannelParticipant>(0xa0ab6cc6, "channels::GetParticipant");
    roundtrip::<bool>(0xa850a693, "channels::ReportAntiSpamFalsePositive");
    roundtrip::<tl::enums::Updates>(0xad399cee, "channels::SetBoostsToUnblockRestrictions");
    roundtrip::<tl::enums::messages::Messages>(0xad8c9a23, "channels::GetMessages");
    roundtrip::<bool>(0xb45ced1d, "channels::ReorderUsernames");
    roundtrip::<tl::enums::Updates>(0xc0111fe3, "channels::DeleteChannel");
    roundtrip::<tl::enums::messages::InvitedUsers>(0xc9e33d54, "channels::InviteToChannel");
    roundtrip::<bool>(0xcc104937, "channels::ReadHistory");
    roundtrip::<tl::enums::Updates>(0xd8aa3671, "channels::UpdateColor");
    roundtrip::<tl::enums::Updates>(0xe4cb9580, "channels::ToggleJoinToSend");
    roundtrip::<tl::enums::ExportedMessageLink>(0xe63fadeb, "channels::ExportMessageLink");
    roundtrip::<tl::enums::channels::SendAsPeers>(0xe785a43f, "channels::GetSendAs");
    roundtrip::<bool>(0xea8ca4f9, "channels::SetStickers");
    roundtrip::<bool>(0xeab5dc38, "channels::ReadMessageContents");
    roundtrip::<tl::enums::Updates>(0xeabbb94c, "channels::TogglePreHistoryHidden");
    roundtrip::<tl::enums::User>(0xece2a0e6, "channels::GetMessageAuthor");
    roundtrip::<tl::enums::Updates>(0xedd49ef0, "channels::ToggleSlowMode");
    roundtrip::<tl::enums::Updates>(0xf0d3e6a8, "channels::UpdateEmojiStatus");
    roundtrip::<tl::enums::Updates>(0xf12e57c9, "channels::EditPhoto");
    roundtrip::<tl::enums::messages::Messages>(0xf2c4f24d, "channels::SearchPosts");
    roundtrip::<bool>(0xf44a8315, "channels::ReportSpam");
    roundtrip::<tl::enums::messages::Chats>(0xf5dad378, "channels::GetGroupsForDiscussion");
    roundtrip::<tl::enums::Updates>(0xf836aa95, "channels::LeaveChannel");
    roundtrip::<tl::enums::messages::Chats>(0xf8b036af, "channels::GetAdminedPublicChannels");
}

#[test]
fn namespace_chatlists() {
    roundtrip::<tl::enums::chatlists::ChatlistInvite>(0x41c10fff, "chatlists::CheckChatlistInvite");
    roundtrip::<tl::enums::ExportedChatlistInvite>(0x653db63d, "chatlists::EditExportedInvite");
    roundtrip::<bool>(0x66e486fb, "chatlists::HideChatlistUpdates");
    roundtrip::<bool>(0x719c5c5e, "chatlists::DeleteExportedInvite");
    roundtrip::<tl::enums::Updates>(0x74fae13a, "chatlists::LeaveChatlist");
    roundtrip::<tl::enums::chatlists::ExportedChatlistInvite>(
        0x8472478e,
        "chatlists::ExportChatlistInvite",
    );
    roundtrip::<tl::enums::chatlists::ChatlistUpdates>(0x89419521, "chatlists::GetChatlistUpdates");
    roundtrip::<tl::enums::Updates>(0xa6b1e39a, "chatlists::JoinChatlistInvite");
    roundtrip::<tl::enums::chatlists::ExportedInvites>(0xce03da83, "chatlists::GetExportedInvites");
    roundtrip::<tl::enums::Updates>(0xe089f8f5, "chatlists::JoinChatlistUpdates");
    roundtrip::<Vec<tl::enums::Peer>>(0xfdbcd714, "chatlists::GetLeaveChatlistSuggestions");
}

#[test]
fn namespace_contacts() {
    roundtrip::<tl::enums::contacts::Found>(0x5f58d0f, "contacts::Search");
    roundtrip::<tl::enums::Updates>(0x96a0e00, "contacts::DeleteContacts");
    roundtrip::<bool>(0x1013fd9e, "contacts::DeleteByPhones");
    roundtrip::<tl::enums::User>(0x13005788, "contacts::ImportContactToken");
    roundtrip::<bool>(0x139f63fb, "contacts::UpdateContactNote");
    roundtrip::<bool>(0x1ae373ac, "contacts::ResetTopPeerRating");
    roundtrip::<tl::enums::Updates>(0x29a8962c, "contacts::BlockFromReplies");
    roundtrip::<tl::enums::contacts::ImportedContacts>(0x2c800be5, "contacts::ImportContacts");
    roundtrip::<bool>(0x2e2e8734, "contacts::Block");
    roundtrip::<tl::enums::contacts::Contacts>(0x5dd69e12, "contacts::GetContacts");
    roundtrip::<tl::enums::contacts::ResolvedPeer>(0x725afbbc, "contacts::ResolveUsername");
    roundtrip::<Vec<i32>>(0x7adc669d, "contacts::GetContactIds");
    roundtrip::<Vec<tl::enums::SavedContact>>(0x82f1e39f, "contacts::GetSaved");
    roundtrip::<bool>(0x8514bdda, "contacts::ToggleTopPeers");
    roundtrip::<bool>(0x879537f1, "contacts::ResetSaved");
    roundtrip::<tl::enums::contacts::ResolvedPeer>(0x8af94344, "contacts::ResolvePhone");
    roundtrip::<bool>(0x94c65c76, "contacts::SetBlocked");
    roundtrip::<tl::enums::contacts::TopPeers>(0x973478b6, "contacts::GetTopPeers");
    roundtrip::<tl::enums::contacts::Blocked>(0x9a868f80, "contacts::GetBlocked");
    roundtrip::<bool>(0xb550d328, "contacts::Unblock");
    roundtrip::<tl::enums::contacts::SponsoredPeers>(0xb6c8c393, "contacts::GetSponsoredPeers");
    roundtrip::<bool>(0xba6705f0, "contacts::EditCloseFriends");
    roundtrip::<Vec<tl::enums::ContactStatus>>(0xc4a353ee, "contacts::GetStatuses");
    roundtrip::<tl::enums::Updates>(0xd348bc44, "contacts::GetLocated");
    roundtrip::<tl::enums::Updates>(0xd9ba2e54, "contacts::AddContact");
    roundtrip::<tl::enums::contacts::ContactBirthdays>(0xdaeda864, "contacts::GetBirthdays");
    roundtrip::<tl::enums::Updates>(0xf831a20f, "contacts::AcceptContact");
    roundtrip::<tl::enums::ExportedContactToken>(0xf8654027, "contacts::ExportContactToken");
}

#[test]
fn namespace_folders() {
    roundtrip::<tl::enums::Updates>(0x6847d0ab, "folders::EditPeerFolders");
}

#[test]
fn namespace_help() {
    roundtrip::<tl::enums::help::UserInfo>(0x38a08d3, "help::GetUserInfo");
    roundtrip::<bool>(0x1e251c95, "help::HidePromoData");
    roundtrip::<tl::enums::NearestDc>(0x1fb33026, "help::GetNearestDc");
    roundtrip::<tl::enums::help::TermsOfServiceUpdate>(0x2ca51fd1, "help::GetTermsOfServiceUpdate");
    roundtrip::<tl::enums::help::RecentMeUrls>(0x3dc0f114, "help::GetRecentMeUrls");
    roundtrip::<tl::enums::help::DeepLinkInfo>(0x3fedc75f, "help::GetDeepLinkInfo");
    roundtrip::<tl::enums::help::TimezonesList>(0x49b30240, "help::GetTimezonesList");
    roundtrip::<tl::enums::help::InviteText>(0x4d392343, "help::GetInviteText");
    roundtrip::<tl::enums::CdnConfig>(0x52029342, "help::GetCdnConfig");
    roundtrip::<tl::enums::help::AppUpdate>(0x522d5a7d, "help::GetAppUpdate");
    roundtrip::<tl::enums::help::AppConfig>(0x61e3f854, "help::GetAppConfig");
    roundtrip::<tl::enums::help::UserInfo>(0x66b91b70, "help::EditUserInfo");
    roundtrip::<bool>(0x6f02f748, "help::SaveAppLog");
    roundtrip::<tl::enums::help::CountriesList>(0x735787a8, "help::GetCountriesList");
    roundtrip::<tl::enums::help::Support>(0x9cdf08cd, "help::GetSupport");
    roundtrip::<tl::enums::help::PeerColors>(0xabcfa9fd, "help::GetPeerProfileColors");
    roundtrip::<tl::enums::help::PremiumPromo>(0xb81b93d4, "help::GetPremiumPromo");
    roundtrip::<tl::enums::help::PromoData>(0xc0977421, "help::GetPromoData");
    roundtrip::<tl::enums::Config>(0xc4f9186b, "help::GetConfig");
    roundtrip::<tl::enums::help::PassportConfig>(0xc661ad08, "help::GetPassportConfig");
    roundtrip::<tl::enums::help::SupportName>(0xd360e72c, "help::GetSupportName");
    roundtrip::<tl::enums::help::PeerColors>(0xda80f42f, "help::GetPeerColors");
    roundtrip::<bool>(0xec22cfcd, "help::SetBotUpdatesStatus");
    roundtrip::<bool>(0xee72f79a, "help::AcceptTermsOfService");
    roundtrip::<bool>(0xf50dbaa1, "help::DismissSuggestion");
}

#[test]
fn namespace_langpack() {
    roundtrip::<Vec<tl::enums::LangPackLanguage>>(0x42c6978f, "langpack::GetLanguages");
    roundtrip::<tl::enums::LangPackLanguage>(0x6a596502, "langpack::GetLanguage");
    roundtrip::<tl::enums::LangPackDifference>(0xcd984aa5, "langpack::GetDifference");
    roundtrip::<Vec<tl::enums::LangPackString>>(0xefea3803, "langpack::GetStrings");
    roundtrip::<tl::enums::LangPackDifference>(0xf2f2330a, "langpack::GetLangPack");
}

#[test]
fn namespace_messages() {
    roundtrip::<tl::enums::Updates>(0x330e77f, "messages::SendMedia");
    roundtrip::<tl::enums::messages::FavedStickers>(0x4f1aaa9, "messages::GetFavedStickers");
    roundtrip::<tl::enums::Updates>(0x589ee75, "messages::EditFactCheck");
    roundtrip::<Vec<tl::enums::ReceivedNotifyMessage>>(0x5a954c0, "messages::ReceivedMessages");
    roundtrip::<tl::enums::messages::AffectedHistory>(0x62dd747, "messages::UnpinAllMessages");
    roundtrip::<tl::enums::Updates>(0x81202c9, "messages::SetChatTheme");
    roundtrip::<bool>(0x9c2dd95, "messages::SetBotPrecheckoutResults");
    roundtrip::<tl::enums::WebViewMessageSent>(0xa4314f5, "messages::SendWebViewResultMessage");
    roundtrip::<tl::enums::messages::AffectedMessages>(0xe306d3a, "messages::ReadHistory");
    roundtrip::<tl::enums::Updates>(0xe7841f0, "messages::ReorderPinnedForumTopics");
    roundtrip::<tl::enums::messages::FeaturedStickers>(
        0xecf6736,
        "messages::GetFeaturedEmojiStickers",
    );
    roundtrip::<tl::enums::messages::HighScores>(0xf635e1b, "messages::GetInlineGameHighScores");
    roundtrip::<tl::enums::messages::Messages>(0x107e31a0, "messages::SearchSentMedia");
    roundtrip::<tl::enums::Updates>(0x10ea6184, "messages::SendVote");
    roundtrip::<tl::enums::channels::SponsoredMessageReportResult>(
        0x12cbf0c4,
        "messages::ReportSponsoredMessage",
    );
    roundtrip::<tl::enums::Updates>(0x13704a7c, "messages::ForwardMessages");
    roundtrip::<tl::enums::MessageMedia>(0x14967978, "messages::UploadMedia");
    roundtrip::<tl::enums::EmojiKeywordsDifference>(
        0x1508b6af,
        "messages::GetEmojiKeywordsDifference",
    );
    roundtrip::<bool>(0x15ad9f64, "messages::SetInlineGameScore");
    roundtrip::<tl::enums::AttachMenuBots>(0x16fcc2cb, "messages::GetAttachMenuBots");
    roundtrip::<tl::enums::messages::AffectedHistory>(0x1720b4d8, "messages::ReadPollVotes");
    roundtrip::<tl::enums::Updates>(0x175df251, "messages::UpdatePinnedForumTopic");
    roundtrip::<tl::enums::messages::AvailableReactions>(
        0x18dea0ac,
        "messages::GetAvailableReactions",
    );
    roundtrip::<tl::enums::Updates>(0x19bc4b6d, "messages::AddPollAnswer");
    roundtrip::<bool>(0x1ad4a04a, "messages::UpdateDialogFilter");
    roundtrip::<Vec<tl::enums::messages::SearchCounter>>(0x1bbcf300, "messages::GetSearchCounters");
    roundtrip::<tl::enums::Updates>(0x1bf89d74, "messages::SendMultiMedia");
    roundtrip::<Vec<tl::enums::MessageRange>>(0x1cff7e08, "messages::GetSplitRanges");
    roundtrip::<tl::enums::messages::EmojiGroups>(0x1dd840f5, "messages::GetEmojiStickerGroups");
    roundtrip::<tl::enums::messages::SavedDialogs>(0x1e91fc99, "messages::GetSavedDialogs");
    roundtrip::<Vec<tl::enums::DialogPeer>>(0x21202222, "messages::GetDialogUnreadMarks");
    roundtrip::<tl::enums::messages::EmojiGroups>(
        0x21a548f3,
        "messages::GetEmojiProfilePhotoGroups",
    );
    roundtrip::<tl::enums::Updates>(0x21a61057, "messages::AppendTodoList");
    roundtrip::<tl::enums::messages::Messages>(0x22ddd30c, "messages::GetReplies");
    roundtrip::<tl::enums::WebViewResult>(0x269dc2c1, "messages::RequestWebView");
    roundtrip::<bool>(0x269e3643, "messages::ViewSponsoredMessage");
    roundtrip::<tl::enums::messages::TranscribedAudio>(0x269e9a49, "messages::TranscribeAudio");
    roundtrip::<tl::enums::messages::DhConfig>(0x26cf8950, "messages::GetDhConfig");
    roundtrip::<tl::enums::messages::FoundStickers>(0x29b1c66a, "messages::SearchStickers");
    roundtrip::<tl::enums::messages::Messages>(0x29ee847a, "messages::Search");
    roundtrip::<tl::enums::MessageMedia>(0x2a862092, "messages::UploadImportedMedia");
    roundtrip::<tl::enums::EmojiList>(0x2c11c0d7, "messages::SearchCustomEmoji");
    roundtrip::<tl::enums::messages::EmojiGroups>(0x2ecd56cd, "messages::GetEmojiStatusGroups");
    roundtrip::<tl::enums::Updates>(0x2f98c3d5, "messages::CreateForumTopic");
    roundtrip::<Vec<tl::enums::ReadParticipantDate>>(
        0x31c1c44f,
        "messages::GetMessageReadParticipants",
    );
    roundtrip::<bool>(0x327a30cb, "messages::SaveGif");
    roundtrip::<tl::enums::messages::SentEncryptedMessage>(
        0x32d439a4,
        "messages::SendEncryptedService",
    );
    roundtrip::<tl::enums::messages::HistoryImport>(0x34090c3b, "messages::InitHistoryImport");
    roundtrip::<tl::enums::messages::BotApp>(0x34fdc5c3, "messages::GetBotApp");
    roundtrip::<bool>(0x35436bbc, "messages::DeclineUrlAuth");
    roundtrip::<tl::enums::messages::FoundStickerSets>(0x35705b8a, "messages::SearchStickerSets");
    roundtrip::<tl::enums::EmojiKeywordsDifference>(0x35a0e062, "messages::GetEmojiKeywords");
    roundtrip::<tl::enums::Updates>(0x35ddd674, "messages::EditChatPhoto");
    roundtrip::<tl::enums::messages::SavedReactionTags>(
        0x3637e05b,
        "messages::GetSavedReactionTags",
    );
    roundtrip::<tl::enums::messages::AffectedMessages>(0x36a73f77, "messages::ReadMessageContents");
    roundtrip::<tl::enums::messages::AffectedHistory>(0x36e5bf4d, "messages::ReadMentions");
    roundtrip::<tl::enums::messages::ChatAdminsWithInvites>(
        0x3920e6ef,
        "messages::GetAdminsWithInvites",
    );
    roundtrip::<bool>(0x392718f8, "messages::SaveRecentSticker");
    roundtrip::<tl::enums::messages::Reactions>(0x39461db2, "messages::GetRecentReactions");
    roundtrip::<bool>(0x3b1adf37, "messages::ReorderPinnedDialogs");
    roundtrip::<tl::enums::User>(0x3b7d0ea6, "messages::GetFutureChatCreatorAfterLeave");
    roundtrip::<tl::enums::messages::ForumTopics>(0x3ba47bff, "messages::GetForumTopics");
    roundtrip::<bool>(0x3cc04740, "messages::DeleteQuickReplyShortcut");
    roundtrip::<tl::enums::messages::SponsoredMessages>(
        0x3d6ce850,
        "messages::GetSponsoredMessages",
    );
    roundtrip::<tl::enums::EncryptedChat>(0x3dbc0415, "messages::AcceptEncryption");
    roundtrip::<tl::enums::ChatInvite>(0x3eadb1bb, "messages::CheckChatInvite");
    roundtrip::<bool>(0x3f64c076, "messages::ReportReaction");
    roundtrip::<bool>(0x4067c5e6, "messages::ReportReadMetrics");
    roundtrip::<tl::enums::WebViewResult>(0x413a3e73, "messages::RequestSimpleWebView");
    roundtrip::<tl::enums::messages::Messages>(0x43286cf2, "messages::GetUnreadPollVotes");
    roundtrip::<bool>(0x435885b5, "messages::TogglePaidReactionPrivacy");
    roundtrip::<tl::enums::messages::HistoryImportParsed>(
        0x43fe19f3,
        "messages::CheckHistoryImport",
    );
    roundtrip::<tl::enums::messages::Messages>(0x4423e6c5, "messages::GetHistory");
    roundtrip::<tl::enums::messages::DiscussionMessage>(
        0x446972fd,
        "messages::GetDiscussionMessage",
    );
    roundtrip::<tl::enums::messages::SentEncryptedMessage>(0x44fa7a15, "messages::SendEncrypted");
    roundtrip::<tl::enums::messages::MessageReactionsList>(
        0x461b3f48,
        "messages::GetMessageReactionsList",
    );
    roundtrip::<tl::enums::Updates>(0x472455aa, "messages::GetPaidReactionPrivacy");
    roundtrip::<tl::enums::messages::Chats>(0x49e9528f, "messages::GetChats");
    roundtrip::<bool>(0x4b0c8c0f, "messages::ReportEncryptedSpam");
    roundtrip::<tl::enums::messages::Messages>(0x4bc6589a, "messages::SearchGlobal");
    roundtrip::<tl::enums::messages::AffectedHistory>(0x4dc5085f, "messages::DeleteSavedHistory");
    roundtrip::<Vec<tl::enums::EmojiLanguage>>(0x4e9963b2, "messages::GetEmojiKeywordsLanguages");
    roundtrip::<bool>(0x4f47a016, "messages::SetDefaultReaction");
    roundtrip::<bool>(0x4facb138, "messages::HidePeerSettingsBar");
    roundtrip::<tl::enums::messages::Messages>(0x501569cf, "messages::GetRichMessage");
    roundtrip::<tl::enums::EncryptedFile>(0x5057c497, "messages::UploadEncryptedFile");
    roundtrip::<tl::enums::messages::BotResults>(0x514e999d, "messages::GetInlineBotResults");
    roundtrip::<tl::enums::WebViewResult>(0x53618bce, "messages::RequestAppWebView");
    roundtrip::<tl::enums::messages::SentEncryptedMessage>(
        0x5559481d,
        "messages::SendEncryptedFile",
    );
    roundtrip::<Vec<i64>>(0x55a5bb66, "messages::ReceivedQueue");
    roundtrip::<tl::enums::messages::Messages>(0x55fb0996, "messages::GetPersonalChannelHistory");
    roundtrip::<bool>(0x56987bd5, "messages::DeleteRevokedExportedChatInvites");
    roundtrip::<tl::enums::messages::WebPagePreview>(0x570d6f6f, "messages::GetWebPagePreview");
    roundtrip::<tl::enums::messages::MessageViews>(0x5784d3e1, "messages::GetMessagesViews");
    roundtrip::<tl::enums::messages::ArchivedStickers>(0x57f17692, "messages::GetArchivedStickers");
    roundtrip::<bool>(0x58943ee2, "messages::SetTyping");
    roundtrip::<tl::enums::Updates>(0x58bbcb50, "messages::SendPaidReaction");
    roundtrip::<tl::enums::Updates>(0x59ae2b16, "messages::DeleteScheduledMessages");
    roundtrip::<bool>(0x5a6d7395, "messages::ReportMessagesDelivery");
    roundtrip::<bool>(0x5b118126, "messages::ReadFeaturedStickers");
    roundtrip::<bool>(0x5bd0ee50, "messages::DeleteChat");
    roundtrip::<bool>(0x5c003cef, "messages::EditQuickReplyShortcut");
    roundtrip::<tl::enums::messages::SavedGifs>(0x5cf09635, "messages::GetSavedGifs");
    roundtrip::<tl::enums::messages::CheckedHistoryImportPeer>(
        0x5dc60f03,
        "messages::CheckHistoryImportPeer",
    );
    roundtrip::<bool>(0x60297dec, "messages::UpdateSavedReactionTag");
    roundtrip::<bool>(0x60331907, "messages::ReorderQuickReplies");
    roundtrip::<tl::enums::messages::Messages>(0x63c66506, "messages::GetMessages");
    roundtrip::<tl::enums::messages::AllStickers>(0x640f82b8, "messages::GetMaskStickers");
    roundtrip::<tl::enums::messages::FeaturedStickers>(0x64780b14, "messages::GetFeaturedStickers");
    roundtrip::<tl::enums::DefaultHistoryTtl>(0x658b7188, "messages::GetDefaultHistoryTtl");
    roundtrip::<tl::enums::UrlAuthResult>(0x67a3f0de, "messages::AcceptUrlAuth");
    roundtrip::<bool>(0x69f59d69, "messages::ToggleBotInAttachMenu");
    roundtrip::<tl::enums::Updates>(0x6a3f8d65, "messages::GetAllDrafts");
    roundtrip::<tl::enums::messages::SearchResultsCalendar>(
        0x6aa3f6bd,
        "messages::GetSearchResultsCalendar",
    );
    roundtrip::<tl::enums::Updates>(0x6c5cf2a7, "messages::SendBotRequestedPeer");
    roundtrip::<tl::enums::Updates>(0x6c750de1, "messages::SendQuickReplyMessages");
    roundtrip::<tl::enums::ChatOnlines>(0x6e2be050, "messages::GetOnlines");
    roundtrip::<tl::enums::messages::SavedDialogs>(0x6f6f9c96, "messages::GetSavedDialogsById");
    roundtrip::<tl::enums::messages::Messages>(0x702a40e0, "messages::GetRecentLocations");
    roundtrip::<tl::enums::messages::ExportedChatInvite>(
        0x73746f5c,
        "messages::GetExportedChatInvite",
    );
    roundtrip::<tl::enums::Updates>(0x73783ffd, "messages::EditChatTitle");
    roundtrip::<tl::enums::messages::EmojiGroups>(0x7488ce5b, "messages::GetEmojiGroups");
    roundtrip::<tl::enums::AttachMenuBotsBot>(0x77216192, "messages::GetAttachMenuBot");
    roundtrip::<bool>(0x78337739, "messages::ReorderStickerSets");
    roundtrip::<bool>(0x791451ed, "messages::SetEncryptedTyping");
    roundtrip::<bool>(0x7e58ee9c, "messages::ClearAllDrafts");
    roundtrip::<tl::enums::messages::FeaturedStickers>(
        0x7ed094a1,
        "messages::GetOldFeaturedStickers",
    );
    roundtrip::<bool>(0x7f1d072f, "messages::RateTranscribedAudio");
    roundtrip::<bool>(0x7f4b690a, "messages::ReadEncryptedHistory");
    roundtrip::<tl::enums::Updates>(0x7fe7e815, "messages::HideChatJoinRequest");
    roundtrip::<tl::enums::Updates>(0x8107455c, "messages::ToggleSuggestedPostApproval");
    roundtrip::<bool>(0x8235057e, "messages::ClickSponsoredMessage");
    roundtrip::<tl::enums::Updates>(0x84f80814, "messages::GetExtendedMedia");
    roundtrip::<tl::enums::messages::PreparedInlineMessage>(
        0x857ebdb8,
        "messages::GetPreparedInlineMessage",
    );
    roundtrip::<tl::enums::Updates>(0x864b2581, "messages::SetChatAvailableReactions");
    roundtrip::<tl::enums::UrlAuthResult>(0x894cc99c, "messages::RequestUrlAuth");
    roundtrip::<bool>(0x8999602d, "messages::ClearRecentStickers");
    roundtrip::<bool>(0x8b716587, "messages::ReorderPinnedSavedDialogs");
    roundtrip::<tl::enums::Updates>(0x8bba90e6, "messages::GetMessagesReactions");
    roundtrip::<tl::enums::OutboxReadDate>(0x8c4bfe5d, "messages::GetOutboxReadDate");
    roundtrip::<bool>(0x8c5006f8, "messages::MarkDialogUnread");
    roundtrip::<tl::enums::messages::WebPage>(0x8d9692a3, "messages::GetWebPage");
    roundtrip::<tl::enums::Updates>(0x8ef8ecc0, "messages::SetGameScore");
    roundtrip::<tl::enums::Updates>(0x8ffacae1, "messages::SetChatWallPaper");
    roundtrip::<tl::enums::messages::FoundStickerSets>(
        0x92b4494c,
        "messages::SearchEmojiStickerSets",
    );
    roundtrip::<tl::enums::messages::InvitedUsers>(0x92ceddd4, "messages::CreateChat");
    roundtrip::<tl::enums::messages::BotCallbackAnswer>(
        0x9342ca07,
        "messages::GetBotCallbackAnswer",
    );
    roundtrip::<tl::enums::messages::Messages>(0x94a495c3, "messages::GetQuickReplyMessages");
    roundtrip::<tl::enums::messages::Messages>(0x998ab009, "messages::GetSavedHistory");
    roundtrip::<tl::enums::messages::SearchResultsPositions>(
        0x9c7f2f10,
        "messages::GetSearchResultsPositions",
    );
    roundtrip::<tl::enums::messages::RecentStickers>(0x9da9403b, "messages::GetRecentStickers");
    roundtrip::<bool>(0x9dfeefb4, "messages::ClearRecentReactions");
    roundtrip::<bool>(0x9eb51445, "messages::SetDefaultHistoryTtl");
    roundtrip::<tl::enums::messages::AffectedHistory>(0x9ec44f93, "messages::ReadReactions");
    roundtrip::<tl::enums::Updates>(0xa00f32b0, "messages::EditChatParticipantRank");
    roundtrip::<bool>(0xa0b80cf8, "messages::DeleteParticipantReactions");
    roundtrip::<tl::enums::messages::Dialogs>(0xa0f4cb4f, "messages::GetDialogs");
    roundtrip::<tl::enums::Updates>(0xa1405817, "messages::SendScreenshotNotification");
    roundtrip::<tl::enums::Updates>(0xa2185cab, "messages::DeleteChatUser");
    roundtrip::<tl::enums::Updates>(0xa2875319, "messages::MigrateChat");
    roundtrip::<Vec<tl::enums::DialogFilterSuggested>>(
        0xa29cd42c,
        "messages::GetSuggestedDialogFilters",
    );
    roundtrip::<tl::enums::messages::ExportedChatInvites>(
        0xa2b5a3f6,
        "messages::GetExportedChatInvites",
    );
    roundtrip::<bool>(0xa423bb51, "messages::EditInlineBotMessage");
    roundtrip::<tl::enums::ExportedChatInvite>(0xa455de90, "messages::ExportChatInvite");
    roundtrip::<tl::enums::Updates>(0xa5866b41, "messages::EditChatDefaultBannedRights");
    roundtrip::<tl::enums::messages::TranslatedText>(0xa5eec345, "messages::TranslateText");
    roundtrip::<bool>(0xa731e257, "messages::ToggleDialogPin");
    roundtrip::<bool>(0xa85bd1c2, "messages::EditChatAdmin");
    roundtrip::<tl::enums::TextWithEntities>(0xabbbd346, "messages::SummarizeText");
    roundtrip::<bool>(0xac81bbde, "messages::ToggleSavedDialogPin");
    roundtrip::<tl::enums::Updates>(0xac8505a5, "messages::DeletePollAnswer");
    roundtrip::<bool>(0xad0fa15c, "messages::SaveDraft");
    roundtrip::<tl::enums::messages::ChatFull>(0xaeb00b34, "messages::GetFullChat");
    roundtrip::<tl::enums::messages::ForumTopics>(0xaf0a4a08, "messages::GetForumTopicsById");
    roundtrip::<tl::enums::messages::AffectedHistory>(0xb08f922a, "messages::DeleteHistory");
    roundtrip::<bool>(0xb0d81a83, "messages::ProlongWebView");
    roundtrip::<tl::enums::Updates>(0xb106e66c, "messages::EditMessage");
    roundtrip::<tl::enums::Document>(0xb1f2061f, "messages::GetDocumentByHash");
    roundtrip::<tl::enums::Updates>(0xb2081a35, "messages::ToggleNoForwards");
    roundtrip::<bool>(0xb43df344, "messages::StartHistoryImport");
    roundtrip::<bool>(0xb5052fea, "messages::ToggleStickerSets");
    roundtrip::<tl::enums::Updates>(0xb80e5fe4, "messages::SetHistoryTtl");
    roundtrip::<tl::enums::messages::VotesList>(0xb86e380e, "messages::GetPollVotes");
    roundtrip::<tl::enums::messages::AllStickers>(0xb8a0a1a8, "messages::GetAllStickers");
    roundtrip::<tl::enums::InputBotInlineMessageId>(0xb8f106e3, "messages::SetBotGuestChatResult");
    roundtrip::<Vec<tl::enums::FactCheck>>(0xb9cdc5ee, "messages::GetFactCheck");
    roundtrip::<bool>(0xb9ffc55b, "messages::FaveSticker");
    roundtrip::<bool>(0xba4a3b5b, "messages::ReadSavedHistory");
    roundtrip::<bool>(0xbb12a419, "messages::SetInlineBotResults");
    roundtrip::<tl::enums::messages::Reactions>(0xbb8125ba, "messages::GetTopReactions");
    roundtrip::<tl::enums::Updates>(0xbd38850a, "messages::SendScheduledMessages");
    roundtrip::<tl::enums::messages::Messages>(0xbd7f90ac, "messages::GetUnreadReactions");
    roundtrip::<tl::enums::messages::Messages>(0xbdbb0464, "messages::GetScheduledMessages");
    roundtrip::<tl::enums::messages::ExportedChatInvite>(
        0xbdca2f75,
        "messages::EditExportedChatInvite",
    );
    roundtrip::<tl::enums::messages::Reactions>(0xbdf93428, "messages::GetDefaultTagReactions");
    roundtrip::<tl::enums::Updates>(0xc0cf7646, "messages::SendInlineBotResult");
    roundtrip::<bool>(0xc563c1e4, "messages::UpdateDialogFiltersOrder");
    roundtrip::<tl::enums::messages::StickerSetInstallResult>(
        0xc78fe460,
        "messages::InstallStickerSet",
    );
    roundtrip::<tl::enums::messages::StickerSet>(0xc8a0ec74, "messages::GetStickerSet");
    roundtrip::<bool>(0xc9a47b0b, "messages::CheckUrlAuthMatchCode");
    roundtrip::<tl::enums::WebViewResult>(0xc9e01e7b, "messages::RequestMainWebView");
    roundtrip::<tl::enums::messages::InvitedUsers>(0xcbc6d107, "messages::AddChatUser");
    roundtrip::<Vec<tl::enums::StickerSetCovered>>(0xcc5b67cc, "messages::GetAttachedStickers");
    roundtrip::<bool>(0xccfddf96, "messages::SaveDefaultSendAs");
    roundtrip::<tl::enums::Updates>(0xcecc1134, "messages::EditForumTopic");
    roundtrip::<bool>(0xcf1592db, "messages::ReportSpam");
    roundtrip::<tl::enums::messages::MyStickers>(0xd0b5e1fc, "messages::GetMyStickers");
    roundtrip::<tl::enums::Updates>(0xd1da940c, "messages::DeleteFactCheck");
    roundtrip::<tl::enums::messages::AffectedHistory>(0xd2816f10, "messages::DeleteTopicHistory");
    roundtrip::<tl::enums::Updates>(0xd2aaf7ec, "messages::UpdatePinnedMessage");
    roundtrip::<tl::enums::Updates>(0xd30d78d4, "messages::SendReaction");
    roundtrip::<tl::enums::Updates>(0xd3e03124, "messages::ToggleTodoCompleted");
    roundtrip::<bool>(0xd464a42b, "messages::DeleteExportedChatInvite");
    roundtrip::<tl::enums::messages::QuickReplies>(0xd483f2a8, "messages::GetQuickReplies");
    roundtrip::<bool>(0xd58f130a, "messages::SetBotCallbackAnswer");
    roundtrip::<tl::enums::messages::Stickers>(0xd5a5d3a1, "messages::GetStickers");
    roundtrip::<tl::enums::EmojiUrl>(0xd5b10c26, "messages::GetEmojiUrl");
    roundtrip::<tl::enums::messages::SavedDialogs>(0xd63d94e0, "messages::GetPinnedSavedDialogs");
    roundtrip::<tl::enums::messages::PeerDialogs>(0xd6b94df2, "messages::GetPinnedDialogs");
    roundtrip::<Vec<tl::enums::Document>>(0xd9ab0f54, "messages::GetCustomEmojiDocuments");
    roundtrip::<tl::enums::messages::ComposedMessageWithAi>(
        0xdaecc589,
        "messages::ComposeMessageWithAi",
    );
    roundtrip::<tl::enums::Updates>(0xdc0242c8, "messages::SendWebViewData");
    roundtrip::<bool>(0xddbcd819, "messages::ReportMusicListen");
    roundtrip::<tl::enums::messages::ChatInviteJoinResult>(
        0xde91436e,
        "messages::ImportChatInvite",
    );
    roundtrip::<tl::enums::messages::AvailableEffects>(0xdea20a39, "messages::GetAvailableEffects");
    roundtrip::<bool>(0xdef60797, "messages::EditChatAbout");
    roundtrip::<tl::enums::messages::ChatInviteImporters>(
        0xdf04dd4e,
        "messages::GetChatInviteImporters",
    );
    roundtrip::<tl::enums::Updates>(0xe085f4ea, "messages::HideAllChatJoinRequests");
    roundtrip::<tl::enums::Updates>(0xe105e910, "messages::DeleteQuickReplyMessages");
    roundtrip::<tl::enums::Updates>(0xe3b7f82c, "messages::DeleteParticipantReaction");
    roundtrip::<tl::enums::messages::Chats>(0xe40ca104, "messages::GetCommonChats");
    roundtrip::<tl::enums::messages::PeerDialogs>(0xe470bcfd, "messages::GetPeerDialogs");
    roundtrip::<bool>(0xe47cb579, "messages::TogglePeerTranslations");
    roundtrip::<tl::enums::messages::AffectedMessages>(0xe58e95d2, "messages::DeleteMessages");
    roundtrip::<bool>(0xe5f672fa, "messages::SetBotShippingResults");
    roundtrip::<tl::enums::Updates>(0xe6df7378, "messages::StartBot");
    roundtrip::<tl::enums::messages::HighScores>(0xe822649d, "messages::GetGameHighScores");
    roundtrip::<tl::enums::Updates>(0xeda3e33b, "messages::GetPollResults");
    roundtrip::<tl::enums::messages::DialogFilters>(0xefd48c89, "messages::GetDialogFilters");
    roundtrip::<tl::enums::messages::PeerSettings>(0xefd9a6a2, "messages::GetPeerSettings");
    roundtrip::<tl::enums::messages::Messages>(0xf107e790, "messages::GetUnreadMentions");
    roundtrip::<bool>(0xf1d0fbd3, "messages::CheckQuickReplyShortcut");
    roundtrip::<tl::enums::messages::BotPreparedInlineMessage>(
        0xf21f7f2f,
        "messages::SavePreparedInlineMessage",
    );
    roundtrip::<bool>(0xf393aea0, "messages::DiscardEncryption");
    roundtrip::<tl::enums::messages::Messages>(0xf516760b, "messages::GetScheduledHistory");
    roundtrip::<tl::enums::EncryptedChat>(0xf64daf43, "messages::RequestEncryption");
    roundtrip::<bool>(0xf731a9f4, "messages::ReadDiscussion");
    roundtrip::<tl::enums::Updates>(0xf743b857, "messages::EditChatCreator");
    roundtrip::<bool>(0xf96e55de, "messages::UninstallStickerSet");
    roundtrip::<tl::enums::messages::AffectedFoundMessages>(
        0xf9cbe409,
        "messages::DeletePhoneCallHistory",
    );
    roundtrip::<tl::enums::messages::EmojiGameInfo>(0xfb7e8ca7, "messages::GetEmojiGameInfo");
    roundtrip::<tl::enums::messages::AllStickers>(0xfbfca18f, "messages::GetEmojiStickers");
    roundtrip::<tl::enums::ReportResult>(0xfc78af9b, "messages::Report");
    roundtrip::<bool>(0xfd2dda49, "messages::ToggleDialogFilterTags");
    roundtrip::<tl::enums::messages::MessageEditData>(0xfda68d36, "messages::GetMessageEditData");
    roundtrip::<tl::enums::Updates>(0xfef48f62, "messages::SendMessage");
}

#[test]
fn namespace_photos() {
    roundtrip::<tl::enums::photos::Photo>(0x388a3b5, "photos::UploadProfilePhoto");
    roundtrip::<tl::enums::photos::Photo>(0x9e82039, "photos::UpdateProfilePhoto");
    roundtrip::<Vec<i64>>(0x87cf7f2f, "photos::DeletePhotos");
    roundtrip::<tl::enums::photos::Photos>(0x91cd32a8, "photos::GetUserPhotos");
    roundtrip::<tl::enums::photos::Photo>(0xe14c4a71, "photos::UploadContactProfilePhoto");
}

#[test]
fn namespace_stats() {
    roundtrip::<tl::enums::stats::StoryStats>(0x374fef40, "stats::GetStoryStats");
    roundtrip::<tl::enums::stats::PublicForwards>(0x5f150144, "stats::GetMessagePublicForwards");
    roundtrip::<tl::enums::StatsGraph>(0x621d5fa0, "stats::LoadAsyncGraph");
    roundtrip::<tl::enums::stats::PublicForwards>(0xa6437ef6, "stats::GetStoryPublicForwards");
    roundtrip::<tl::enums::stats::BroadcastStats>(0xab42441a, "stats::GetBroadcastStats");
    roundtrip::<tl::enums::stats::MessageStats>(0xb6e0a3f5, "stats::GetMessageStats");
    roundtrip::<tl::enums::stats::PollStats>(0xc27dfa68, "stats::GetPollStats");
    roundtrip::<tl::enums::stats::MegagroupStats>(0xdcdf8607, "stats::GetMegagroupStats");
}

#[test]
fn namespace_stickers() {
    roundtrip::<tl::enums::messages::StickerSet>(0x124b1c00, "stickers::RenameStickerSet");
    roundtrip::<bool>(0x284b3639, "stickers::CheckShortName");
    roundtrip::<tl::enums::messages::StickerSet>(0x4696459a, "stickers::ReplaceSticker");
    roundtrip::<tl::enums::stickers::SuggestedShortName>(0x4dafc503, "stickers::SuggestShortName");
    roundtrip::<tl::enums::messages::StickerSet>(0x8653febe, "stickers::AddStickerToSet");
    roundtrip::<bool>(0x87704394, "stickers::DeleteStickerSet");
    roundtrip::<tl::enums::messages::StickerSet>(0x9021ab67, "stickers::CreateStickerSet");
    roundtrip::<tl::enums::messages::StickerSet>(0xa76a5392, "stickers::SetStickerSetThumb");
    roundtrip::<tl::enums::messages::StickerSet>(0xf5537ebc, "stickers::ChangeSticker");
    roundtrip::<tl::enums::messages::StickerSet>(0xf7760f51, "stickers::RemoveStickerFromSet");
    roundtrip::<tl::enums::messages::StickerSet>(0xffb6d4ca, "stickers::ChangeStickerPosition");
}

#[test]
fn namespace_stories() {
    roundtrip::<bool>(0xb297e9b, "stories::TogglePinnedToTop");
    roundtrip::<tl::enums::ReportResult>(0x19d8eb45, "stories::Report");
    roundtrip::<tl::enums::stories::Albums>(0x25b3eac7, "stories::GetAlbums");
    roundtrip::<tl::enums::stories::StoryViews>(0x28e16cc8, "stories::GetStoriesViews");
    roundtrip::<tl::enums::stories::PeerStories>(0x2c4ada50, "stories::GetPeerStories");
    roundtrip::<tl::enums::Updates>(0x2c63a72b, "stories::EditStory");
    roundtrip::<tl::enums::stories::CanSendStoryCount>(0x30eb63f0, "stories::CanSendStory");
    roundtrip::<tl::enums::stories::Stories>(0x5774ca74, "stories::GetStoriesById");
    roundtrip::<tl::enums::Updates>(0x57bbd166, "stories::ActivateStealthMode");
    roundtrip::<tl::enums::stories::Stories>(0x5821a5dc, "stories::GetPinnedStories");
    roundtrip::<tl::enums::StoryAlbum>(0x5e5259b6, "stories::UpdateAlbum");
    roundtrip::<Vec<tl::enums::RecentStory>>(0x78499170, "stories::GetPeerMaxIds");
    roundtrip::<tl::enums::ExportedStoryLink>(0x7b8def20, "stories::ExportStoryLink");
    roundtrip::<bool>(0x7c2557c4, "stories::ToggleAllStoriesHidden");
    roundtrip::<tl::enums::stories::StoryViewsList>(0x7ed23c57, "stories::GetStoryViewsList");
    roundtrip::<tl::enums::Updates>(0x7fd736b2, "stories::SendReaction");
    roundtrip::<bool>(0x8535fbd9, "stories::ReorderAlbums");
    roundtrip::<bool>(0x8d3456d0, "stories::DeleteAlbum");
    roundtrip::<tl::enums::Updates>(0x8f9e6898, "stories::SendStory");
    roundtrip::<Vec<i32>>(0x9a75a1ef, "stories::TogglePinned");
    roundtrip::<tl::enums::Updates>(0x9b5ae7f9, "stories::GetAllReadPeerStories");
    roundtrip::<tl::enums::StoryAlbum>(0xa36396e5, "stories::CreateAlbum");
    roundtrip::<Vec<i32>>(0xa556dac8, "stories::ReadStories");
    roundtrip::<tl::enums::messages::Chats>(0xa56a8b60, "stories::GetChatsToSend");
    roundtrip::<tl::enums::stories::Stories>(0xac806d61, "stories::GetAlbumStories");
    roundtrip::<Vec<i32>>(0xae59db5f, "stories::DeleteStories");
    roundtrip::<bool>(0xb2028afb, "stories::IncrementStoryViews");
    roundtrip::<tl::enums::stories::Stories>(0xb4352016, "stories::GetStoriesArchive");
    roundtrip::<tl::enums::stories::StoryReactionsList>(
        0xb9b2881f,
        "stories::GetStoryReactionsList",
    );
    roundtrip::<bool>(0xbd0415c4, "stories::TogglePeerStoriesHidden");
    roundtrip::<tl::enums::Updates>(0xd069ccde, "stories::StartLive");
    roundtrip::<tl::enums::stories::FoundStories>(0xd1810907, "stories::SearchPosts");
    roundtrip::<tl::enums::stories::AllStories>(0xeeb0d625, "stories::GetAllStories");
}

#[test]
fn namespace_updates() {
    roundtrip::<tl::enums::updates::ChannelDifference>(0x3173d78, "updates::GetChannelDifference");
    roundtrip::<tl::enums::updates::Difference>(0x19c2f763, "updates::GetDifference");
    roundtrip::<tl::enums::updates::State>(0xedd4882a, "updates::GetState");
}

#[test]
fn namespace_upload() {
    roundtrip::<tl::enums::upload::WebFile>(0x24e6818d, "upload::GetWebFile");
    roundtrip::<tl::enums::upload::CdnFile>(0x395f69da, "upload::GetCdnFile");
    roundtrip::<Vec<tl::enums::FileHash>>(0x9156982a, "upload::GetFileHashes");
    roundtrip::<Vec<tl::enums::FileHash>>(0x91dc3f31, "upload::GetCdnFileHashes");
    roundtrip::<Vec<tl::enums::FileHash>>(0x9b2754a8, "upload::ReuploadCdnFile");
    roundtrip::<bool>(0xb304a621, "upload::SaveFilePart");
    roundtrip::<tl::enums::upload::File>(0xbe5335be, "upload::GetFile");
    roundtrip::<bool>(0xde7b673d, "upload::SaveBigFilePart");
}

#[test]
fn namespace_users() {
    roundtrip::<Vec<tl::enums::User>>(0xd91a548, "users::GetUsers");
    roundtrip::<tl::enums::users::SavedMusic>(0x7573a4e9, "users::GetSavedMusicById");
    roundtrip::<tl::enums::users::SavedMusic>(0x788d7fe3, "users::GetSavedMusic");
    roundtrip::<bool>(0x90c894b5, "users::SetSecureValueErrors");
    roundtrip::<tl::enums::users::UserFull>(0xb60f5918, "users::GetFullUser");
    roundtrip::<Vec<tl::enums::RequirementToContact>>(
        0xd89a83a3,
        "users::GetRequirementsToContact",
    );
    roundtrip::<tl::enums::Updates>(0xfc533372, "users::SuggestBirthday");
}

#[test]
fn coverage_matches_constant() {
    assert_eq!(compat::DEFAULT_RESPONSE_METHODS, 660);
}

#[test]
fn excluded_namespaces_are_not_stubbed() {
    for ctor in [0x00000000u32, 0xffffffffu32] {
        assert!(compat::default_response(ctor).is_none());
    }
    for ns in compat::UNSUPPORTED_NAMESPACES {
        assert!([
            "aicompose",
            "fragment",
            "payments",
            "phone",
            "premium",
            "smsjobs"
        ]
        .contains(ns));
    }
    // Excluded methods must not appear in the compatibility table.
    let stubbed: Vec<u32> = vec![
        0x32512c5, 0x41845db, 0x42f1f61, 0x93fa0bf, 0xbe77b4a, 0xd6b48f7, 0xedc39d0, 0xf91b065,
        0x10a698e8, 0x1513e7b0, 0x1782cbb1, 0x17d54f61, 0x1ab21940, 0x1c50d144, 0x1ca6ac0a,
        0x1dbfeca0, 0x1f4a0e87, 0x219c34e6, 0x227d824b, 0x2433dc92, 0x2478d1cc, 0x25ae8f4a,
        0x2757ba54, 0x277add7e,
    ];
    for ctor in stubbed {
        assert!(
            compat::default_response(ctor).is_none(),
            "{ctor:#x} should not be stubbed"
        );
    }
}
